/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package trial.java.jasperreport;

import java.util.*;
import java.io.*;
import java.sql.Date;

import com.google.gson.*;
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.view.*;

public class App {
    public static void main(String[] args) {
        System.out.println("jasperreport");
        try {
            // 这个必须独立的文件，不能被打包到 jar 里面。
            JasperReport jr = JasperCompileManager.compileReport("./jrpdemo/src/main/resources/demo.jrxml");
            
            Gson gson = new Gson();
            HashMap<String, Object> d = gson.fromJson(DemoUtil.readResourceString("/demo.json"), HashMap.class);
            Map<String, Object> gy = (Map)d.get("概要"); // 作为参数传入 $P{XXXX}
            gy.put("时间", new Date(System.currentTimeMillis()));
            List<HashMap> a = (List)d.get("数据列表"); // 作为数据源 $F{XXX}
            JRDataSource ds = new JRBeanCollectionDataSource(a);
            JasperPrint jp = JasperFillManager.fillReport(jr, d, ds);
            // JasperExportManager.exportReportToPdfFile(jp, "demo.pdf");
            JasperViewer jv = new JasperViewer(jp, false);
            jv.setVisible(true);
            jv.pack();
        }
         catch (JRException e) {
            e.printStackTrace();
        }
        catch (JsonSyntaxException e) {
            e.printStackTrace();
        }
        catch (IOException e) {
            e.printStackTrace();
        }
    }
}
