/*
 * This C++ source file was generated by the Gradle 'init' task.
 */

#include <iostream>
#include <stdlib.h>
#include "trial-java-jnicpp.h"

std::string trial_java_jnicpp::Greeter::greeting() {
    return std::string("Hello, World!");
}
