/*
 * This C++ source file was generated by the Gradle 'init' task.
 */

#include "trial-java-jnicpp.h"
#include <cassert>

int main() {
    trial_java_jnicpp::Greeter greeter;
    assert(greeter.greeting().compare("Hello, World!") == 0);
    return 0;
}
