/*
 * This C++ source file was generated by the Gradle 'init' task.
 */
#ifndef TRIAL_JAVA_JNICPP_H
#define TRIAL_JAVA_JNICPP_H

#ifdef _WIN32
#define TRIAL_JAVA_JNICPP_EXPORT_FUNC __declspec(dllexport)
#else
#define TRIAL_JAVA_JNICPP_EXPORT_FUNC
#endif

#include <string>

namespace trial_java_jnicpp {
    class Greeter {
        public:
        std::string TRIAL_JAVA_JNICPP_EXPORT_FUNC greeting();
    };
}

#endif
